### PR TITLE
Bugfix/issue646

### LINKED ISSUE #646: Opening/Closing analytic view with graph opened causes RenderExceptions
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Trying to recreate #629 I managed to find a rendering exception.
I used the hotkeys ctrl + shift + z to open analytic view, and closed it via the 'x' button on the tab. I repeated this decently fast and 1/10th of the time I would get this exception. I've recreated it twice within a few minutes.

```
au.gov.asd.tac.constellation.visual.opengl.utilities.RenderException: Incorrect amount of data for the specified target [size=3504, limit=5164, position=0]
	at au.gov.asd.tac.constellation.visual.opengl.renderer.batcher.Batch.bufferData(Batch.java:367)
	at au.gov.asd.tac.constellation.visual.opengl.renderer.batcher.Batch.buffer(Batch.java:296)
	at au.gov.asd.tac.constellation.visual.opengl.renderer.batcher.NodeLabelBatcher.lambda$createBatch$0(NodeLabelBatcher.java:162)
	at au.gov.asd.tac.constellation.visual.opengl.renderer.GraphRenderable.lambda$update$29(GraphRenderable.java:378)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at au.gov.asd.tac.constellation.visual.opengl.renderer.GraphRenderable.update(GraphRenderable.java:377)
	at au.gov.asd.tac.constellation.visual.opengl.renderer.GLRenderer.lambda$display$2(GLRenderer.java:166)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at au.gov.asd.tac.constellation.visual.opengl.renderer.GLRenderer.display(GLRenderer.java:165)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at com.jogamp.opengl.awt.GLCanvas$11.run(GLCanvas.java:1428)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
Caused: com.jogamp.opengl.GLException: Caught RenderException: Incorrect amount of data for the specified target [size=3504, limit=5164, position=0] on thread AWT-EventQueue-0
	at com.jogamp.opengl.GLException.newGLException(GLException.java:76)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1327)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.opengl.awt.GLCanvas$12.run(GLCanvas.java:1442)
	at com.jogamp.opengl.Threading.invoke(Threading.java:223)
	at com.jogamp.opengl.awt.GLCanvas.display(GLCanvas.java:503)
	at com.jogamp.opengl.awt.GLCanvas.paint(GLCanvas.java:557)
	at java.desktop/sun.awt.RepaintArea.paintComponent(RepaintArea.java:264)
	at java.desktop/sun.awt.RepaintArea.paint(RepaintArea.java:240)
	at java.desktop/sun.awt.windows.WComponentPeer.handleEvent(WComponentPeer.java:358)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5069)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
[catch] at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

### Steps to Reproduce

1. open graph and use complete graph builder
2. open new graph and use sphere graph builder
3. ctrl + shift + z to open analytic view 
4. close the view
5. repeat 3 and 4 until exception occurs

**Expected behaviour:** no errors

**Actual behaviour:** render exception

**Reproduces how often:** 10%

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

### PR DESCRIPTION
**Pull request by Nova-2119**
-->

### Applicable Issues

https://github.com/constellation-app/constellation/issues/646
fixes #646

### CODE REVIEW

File: CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/renderer/batcher/NodeLabelBatcher.java [hunk 1]
```diff
@@ -150,12 +146,13 @@ public void createShader(GL3 gl) throws IOException {
 
     @Override
     public GLRenderableUpdateTask createBatch(final VisualAccess access) {
-        topLabelFloats = new FloatArray();
-        topLabelInts = new IntArray();
-        bottomLabelFloats = new FloatArray();
-        bottomLabelInts = new IntArray();
-        fillTopLabels(access);
-        fillBottomLabels(access);
+        FloatArray topLabelFloats = new FloatArray();
```
Comment (cygnus-x-1) [inline CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/renderer/batcher/NodeLabelBatcher.java:149]: finals?

File: CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/renderer/batcher/NodeLabelBatcher.java [hunk 2]
```diff
@@ -196,8 +193,8 @@ public GLRenderableUpdateTask updateBottomLabels(final VisualAccess access) {
             bottomBatch.finalise(gl);
         };
     }
-
-    private void fillTopLabels(final VisualAccess access) {
+    
+    private void fillTopLabels(final VisualAccess access, FloatArray topLabelFloats, IntArray topLabelInts) {
```
Comment (cygnus-x-1) [inline CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/renderer/batcher/NodeLabelBatcher.java:197]: finals.

File: CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/renderer/batcher/NodeLabelBatcher.java [hunk 3]
```diff
@@ -207,7 +204,7 @@ private void fillTopLabels(final VisualAccess access) {
         topLabelInts.trimToSize();
     }
 
-    private void fillBottomLabels(final VisualAccess access) {
+    private void fillBottomLabels(final VisualAccess access, FloatArray bottomLabelFloats, IntArray bottomLabelInts) {
```
Comment (cygnus-x-1) [inline CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/renderer/batcher/NodeLabelBatcher.java:207]: finals.

File: CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/renderer/batcher/NodeLabelBatcher.java (hunk 1 above)
Comment (Nova-2119) [reply CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/renderer/batcher/NodeLabelBatcher.java]: yes and done.

File: CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/renderer/batcher/NodeLabelBatcher.java (hunk 2 above)
Comment (Nova-2119) [reply CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/renderer/batcher/NodeLabelBatcher.java]: Done :)

File: CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/renderer/batcher/NodeLabelBatcher.java (hunk 3 above)
Comment (Nova-2119) [reply CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/renderer/batcher/NodeLabelBatcher.java]: Done

**Review by cygnus-x-1 — APPROVED** [review]

File: CoreUtilities/src/au/gov/asd/tac/constellation/utilities/graphics/FloatArray.java [hunk 4]
```diff
@@ -134,6 +134,7 @@ public FloatArray(final int initialCapacity) {
             throw new IllegalArgumentException("Illegal Capacity: " + initialCapacity);
         }
         this.elementData = new float[initialCapacity];
+        size=0;
```
Comment (antares1470) [inline CoreUtilities/src/au/gov/asd/tac/constellation/utilities/graphics/FloatArray.java:137]: Minor but it might be good to add some spaces here

File: CoreUtilities/src/au/gov/asd/tac/constellation/utilities/graphics/IntArray.java [hunk 5]
```diff
@@ -133,6 +133,7 @@ public IntArray(final int initialCapacity) {
             throw new IllegalArgumentException("Illegal Capacity: " + initialCapacity);
         }
         this.elementData = new int[initialCapacity];
+        size=0;
```
Comment (antares1470) [inline CoreUtilities/src/au/gov/asd/tac/constellation/utilities/graphics/IntArray.java:136]: same here

**Review by antares1470 — APPROVED** [review]

File: CoreUtilities/src/au/gov/asd/tac/constellation/utilities/graphics/FloatArray.java (hunk 4 above)
Comment (Nova-2119) [reply CoreUtilities/src/au/gov/asd/tac/constellation/utilities/graphics/FloatArray.java:139]: See latest changes, I think this is what you meant?

File: CoreUtilities/src/au/gov/asd/tac/constellation/utilities/graphics/IntArray.java (hunk 5 above)
Comment (Nova-2119) [reply CoreUtilities/src/au/gov/asd/tac/constellation/utilities/graphics/IntArray.java:138]: See latest changes, I think this is what you meant?

File: CoreUtilities/src/au/gov/asd/tac/constellation/utilities/graphics/FloatArray.java (hunk 4 above)
Comment (antares1470) [reply CoreUtilities/src/au/gov/asd/tac/constellation/utilities/graphics/FloatArray.java:139]: Not quite. I meant `size=0` becoming `size = 0`

File: CoreUtilities/src/au/gov/asd/tac/constellation/utilities/graphics/IntArray.java (hunk 5 above)
Comment (antares1470) [reply CoreUtilities/src/au/gov/asd/tac/constellation/utilities/graphics/IntArray.java:138]: Not quite. I meant `size=0` becoming `size = 0`
