### PR TITLE
Bugfix/issue727 conversation clear content

### LINKED ISSUE #727: Closing graph doesn't clear content bubbles in Conversation View.
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Closing graph doesn't clear content bubbles in Conversation View. 

### Steps to Reproduce

1. Open a graph with content attributes (conversation bubbles).
2. Open Conversation View.
3. Close graph.

**Expected behaviour:** Content bubbles cleared from Conversation View.

**Actual behaviour:** Content bubbles not cleared from Conversation View.

**Reproduces how often:** 100%
ConversationView_error

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

### PR DESCRIPTION
**Pull request by Nova-2119**
### Benefits
Previous conversation will no longer linger when a graph is closed.

### Possible Drawbacks

Unknown / NA

### Verification Process

Tested opening, modifying and closing graphs in various orders.

### Applicable Issues

fixes #727

### CODE REVIEW

File: CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/Conversation.java [hunk 1]
```diff
@@ -183,17 +201,23 @@ public GraphUpdateManager getGraphUpdateManager() {
...
-            int conversationStateAttribute = ConversationViewConcept.MetaAttribute.CONVERSATION_VIEW_STATE.get(graph);
-            if (conversationStateAttribute == Graph.NOT_FOUND) {
-                newConversationState = new ConversationState();
-                newConversationState.setSenderAttributesToKeys(graph);
-            } else {
-                newConversationState = (ConversationState) graph.getObjectValue(conversationStateAttribute, 0);
-                if (newConversationState == null) {
+            int conversationStateAttribute;
+            if (Objects.nonNull(graph)) {
+                conversationStateAttribute = ConversationViewConcept.MetaAttribute.CONVERSATION_VIEW_STATE.get(graph);
```
Comment (antares1470) [inline CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/Conversation.java:208]: You can declare this variable here (rather than a couple lines above) since it doesn't seem to be used outside this code block. Also can make it final

File: CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/Conversation.java [hunk 2]
```diff
@@ -410,9 +435,9 @@ public void run() {
     private UpdateComponent<GraphReadMethods> senderUpdater = new UpdateComponent<GraphReadMethods>("Senders", LOCK_STAGE) {
         @Override
         protected boolean update(GraphReadMethods graph) {
-            if (graph == null) {
-                return false;
-            }
+//            if (graph == null) {
+//                return false;
+//            }
```
Comment (antares1470) [inline CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/Conversation.java:440]: Can possibly remove commented out code if it's not needed

File: CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/ConversationContributionProvider.java [hunk 3]
```diff
@@ -133,9 +134,11 @@ public final int getPriority() {
      */
     public static List<ConversationContributionProvider> getCompatibleProviders(GraphReadMethods graph) {
         List<ConversationContributionProvider> compatibleProviders = new ArrayList<>();
```
Comment (antares1470) [inline CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/ConversationContributionProvider.java:136]: I know you didn't add this but if you make this final please

File: CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/DefaultConversationDatetimeProvider.java [hunk 4]
```diff
@@ -22,6 +22,7 @@
 import java.time.ZonedDateTime;
 import java.time.format.DateTimeFormatter;
 import java.util.List;
+import java.util.Objects;
```
Comment (antares1470) [inline CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/DefaultConversationDatetimeProvider.java:25]: this import isn't used according to sonar

**Review by antares1470 — CHANGES_REQUESTED** [review]

**Review by mimosa2 — APPROVED** [review]
The conversation content bubbles are now cleared after closing the graph.

File: CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/Conversation.java [hunk 5]
```diff
@@ -174,6 +181,17 @@ public GraphUpdateManager getGraphUpdateManager() {
...
 
+    /**
+     * Inspects the contents of the conversation state and registers any changes
+     * that have occurred.
+     */
+    private UpdateComponent<GraphReadMethods> conversationExistanceUpdater = new UpdateComponent<GraphReadMethods>("Existance State", LOCK_STAGE) {
+
+        @Override
+        protected boolean update(GraphReadMethods graph) {
+            return Objects.isNull(graph);
```
Comment (arcturus2) [inline CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/Conversation.java:192]: Is there any reason you have used `Objects.isNull`?

This is a minor feedback but to me `Objects.isNull` looks a bit out of place given the rest of the code base doesn't use this approach to check for `null`. Are you able to change this to `graph == null` so it looks more familiar? There are several occurrences of this method that would require changing in this PR.

Apparently it is useful inside lambda functions, see https://stackoverflow.com/a/46025437.

**Review by arcturus2 — CHANGES_REQUESTED** [review]
Thanks for this @Nova-2119. I have made a minor comment for you.

File: CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/Conversation.java (hunk 1 above)
Comment (Nova-2119) [reply CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/Conversation.java:208]: done

File: CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/Conversation.java (hunk 2 above)
Comment (Nova-2119) [reply CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/Conversation.java:440]: oh yeah, done

File: CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/ConversationContributionProvider.java (hunk 3 above)
Comment (Nova-2119) [reply CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/ConversationContributionProvider.java:136]: done

File: CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/DefaultConversationDatetimeProvider.java (hunk 4 above)
Comment (Nova-2119) [reply CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/DefaultConversationDatetimeProvider.java:25]: I agree

File: CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/Conversation.java (hunk 5 above)
Comment (Nova-2119) [reply CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/Conversation.java:192]: No meaningful reason, just personal preference. I find it easier to read,

Changed.

File: CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/Conversation.java [hunk 6]
```diff
@@ -183,17 +201,22 @@ public GraphUpdateManager getGraphUpdateManager() {
...
             ConversationState newConversationState;
-            int conversationStateAttribute = ConversationViewConcept.MetaAttribute.CONVERSATION_VIEW_STATE.get(graph);
-            if (conversationStateAttribute == Graph.NOT_FOUND) {
-                newConversationState = new ConversationState();
-                newConversationState.setSenderAttributesToKeys(graph);
-            } else {
-                newConversationState = (ConversationState) graph.getObjectValue(conversationStateAttribute, 0);
-                if (newConversationState == null) {
+            if (Objects.nonNull(graph)) {
+                int conversationStateAttribute = ConversationViewConcept.MetaAttribute.CONVERSATION_VIEW_STATE.get(graph);
```
Comment (antares1470) [inline CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/Conversation.java:207]: final

**Review by antares1470 — CHANGES_REQUESTED** [review]

File: CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/Conversation.java (hunk 6 above)
Comment (Nova-2119) [reply CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/Conversation.java]: final final ?

**Review by antares1470 — APPROVED** [review]

**Review by cygnus-x-1 — APPROVED** [review]

File: CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/Conversation.java [hunk 7]
```diff
@@ -222,12 +245,14 @@ protected boolean update(GraphReadMethods graph) {
         @Override
         protected boolean update(GraphReadMethods graph) {
             possibleSenderAttributes.clear();
-            final int attributeCount = graph.getAttributeCount(GraphElementType.VERTEX);
-            for (int i = 0; i < attributeCount; i++) {
-                final int attributeId = graph.getAttribute(GraphElementType.VERTEX, i);
-                final Attribute attribute = new GraphAttribute(graph, attributeId);
-                if (!ObjectAttributeDescription.class.isAssignableFrom(attribute.getDataType())) {
-                    possibleSenderAttributes.add(attribute.getName());
+            if (Objects.nonNull(graph)) {
```
Comment (antares1470) [inline CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/Conversation.java:248]: `graph != null`

File: CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/ConversationContributionProvider.java [hunk 8]
```diff
@@ -132,10 +133,12 @@ public final int getPriority() {
      * @return A list of all providers that are compatible with the given graph.
      */
     public static List<ConversationContributionProvider> getCompatibleProviders(GraphReadMethods graph) {
-        List<ConversationContributionProvider> compatibleProviders = new ArrayList<>();
-        for (ConversationContributionProvider provider : getProviders()) {
-            if (provider.isCompatibleWithGraph(graph)) {
-                compatibleProviders.add(provider);
+        final List<ConversationContributionProvider> compatibleProviders = new ArrayList<>();
+        if (Objects.nonNull(graph)) {
```
Comment (antares1470) [inline CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/ConversationContributionProvider.java:137]: `graph != null`

File: CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/DefaultConversationColorProvider.java [hunk 9]
```diff
@@ -33,7 +34,11 @@
     @Override
     public void updateMessageColors(GraphReadMethods graph, List<ConversationMessage> messages) {
         assert !SwingUtilities.isEventDispatchThread();
-
+        
+        if (Objects.isNull(graph) || messages.isEmpty()) {
```
Comment (antares1470) [inline CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/DefaultConversationColorProvider.java:38]: `graph == null...`

File: CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/DefaultConversationMessageProvider.java [hunk 10]
```diff
@@ -38,7 +39,10 @@
     @Override
     public void getMessages(GraphReadMethods graph, List<ConversationMessage> messages) {
         assert !SwingUtilities.isEventDispatchThread();
-
+        messages.clear();
+        if (Objects.isNull(graph)) {
```
Comment (antares1470) [inline CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/DefaultConversationMessageProvider.java:43]: `graph == null`

File: CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/DefaultConversationSenderProvider.java [hunk 11]
```diff
@@ -51,6 +52,9 @@
     public void updateMessageSenders(GraphReadMethods graph, List<ConversationMessage> messages, List<String> senderAttributes) {
         assert !SwingUtilities.isEventDispatchThread();
 
+        if(Objects.isNull(graph) || messages.isEmpty()){
```
Comment (antares1470) [inline CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/DefaultConversationSenderProvider.java:55]: `graph == null...`

**Review by antares1470 — CHANGES_REQUESTED** [review]
Talking with @arcturus2 it seems that the preference is to not use the Objects method (which just checks whether the graph is isn't null anyway) since this isn't used else where

**Review by aldebaran30701 — CHANGES_REQUESTED** [review]
In every class committed, there is still a hanging import for java.util.Objects;
I made my Netbeans remove unused imports on save. It's pretty handy.
Looks and works great otherwise!

**Review by aldebaran30701 — APPROVED** [review]

**Review by antares1470 — APPROVED** [review]
