### PR TITLE
Fix #281 Null Pointer

### LINKED ISSUE #281: Null pointer exception when resizing empty graph when Hierarchical Cluster panel is open
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

If Hierarchical view is open for an empty graph and that graph iszoomed in or out an null pointer exception is thrown.

### Steps to Reproduce

1. Open a new graph
2. Select Tools -> Cluster -> Hierarchical
3. Click on the graph and use the mouse wheel to zoom in or out

**Expected behaviour:**
Even though the graph is empty, it should zoom in/out (as its empty there will be no noticable difference)

**Actual behaviour:** 
An error dialog "Hierarchical: Update" is thrown containing text indicating an unexpected error was detected. A further warning dialog is shown saying that a java.lang.RuntimeException was thrown on line 698 CoreAlgorithms\src\au\gov\asd\tac\constellation\algorithms\clustering\hierarchical\HierarchicalControllerTopComponent.java.
This is being thrown as the state varaible is null.

**Reproduces how often:**
100%

### Additional Information

This issue was introduced recently when changes were made to the Hierarchical code in HierarchicalControllerTopComponent.java.

The fix for this error is already known, and based on how KTruss works.

To fix, go to line 554 of HierarchicalControllerTopComponent.java (in method **setGroups**) and change from:
    if (doUpdate) {
to:
    if (**(state != null) &&** doUpdate) {

Justification:
state can be null, we dont want to update nodes in this case .... refer to the method **setGroups** within CoreAlgorithms\src\au\gov\asd\tac\constellation\algorithms\clustering\ktruss\KTrussControllerTopComponent.java which is what the **setGroups** method has been based on.

### PR DESCRIPTION
**Pull request by sol695510**
### Description of the Change
"if" statement condition altered to only execute "doUpdate" if the state is not null. Refer further to "Additional Information" in #281.

### Alternate Designs
N/A

### Why Should This Be In Core?
Because it is a small change to an existing code block.

### Benefits
Scrolling on an empty graph with the Hierarchical view open does not throw a Null Pointer.

### Possible Drawbacks
N/A

### Verification Process
After code change, performed "Steps to Reproduce" and got "Expected behaviour", from #281.

### Applicable Issues
N/A

### CODE REVIEW

File: CoreAlgorithms/src/au/gov/asd/tac/constellation/algorithms/clustering/hierarchical/HierarchicalControllerTopComponent.java [hunk 1]
```diff
@@ -551,7 +551,7 @@ private void setGroups(final boolean doUpdate) {
                 dp.setState(null);
                 revalidateParents(dp);
             }
-            if (doUpdate) {
+            if ((state != null) && doUpdate) {
```
Comment (arcturus2) [inline CoreAlgorithms/src/au/gov/asd/tac/constellation/algorithms/clustering/hierarchical/HierarchicalControllerTopComponent.java]: Thanks @sol695510. Note that the additional parenthesis around the `state != null` is redundant.

Comment (sol695510) [reply CoreAlgorithms/src/au/gov/asd/tac/constellation/algorithms/clustering/hierarchical/HierarchicalControllerTopComponent.java]: Did you want me to remove the brackets? @arcturus2

Comment (arcturus2) [reply CoreAlgorithms/src/au/gov/asd/tac/constellation/algorithms/clustering/hierarchical/HierarchicalControllerTopComponent.java]: If you could that would be great @sol695510 because I reckon Sonar will complain 😄

**Comment by arcturus2** [comment]
Thanks @sol695510
