### PR TITLE
Bugfix/issue826 betweeness assertion error

### LINKED ISSUE #826: Betweeness Centrality AssertionError
### Description

Running the Betweeness Centrality analytic can cause an AssertionError

### Steps to Reproduce

1. Open new graph
2. Place two nodes in the graph with one transaction between them using the draw feature
3. Open analytic view
4. Run Betweeness Centrality analytic

**Expected behaviour:** [What you expect to happen]
No error should occur

**Actual behaviour:** [What actually happens]
Error

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### PR DESCRIPTION
**Pull request by Nova-2119**
# Description of the Change

### Benefits
Reduced chance for error.

### Possible Drawbacks

May hide an unintended NaN value.

### Applicable Issues
Fixes #826

### CODE REVIEW

File: CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/sna/centrality/BetweennessCentralityPlugin.java [hunk 1]
```diff
@@ -153,23 +153,31 @@ public void edit(final GraphWriteMethods graph, final PluginInteraction interact
         // update the graph with betweenness values
         for (int vertexPosition = 0; vertexPosition < vertexCount; vertexPosition++) {
             final int vertexId = graph.getVertex(vertexPosition);
+            float betweennessAttributeValue;
```
Comment (antares1470) [inline CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/sna/centrality/BetweennessCentralityPlugin.java:156]: final

**Review by antares1470 — CHANGES_REQUESTED** [review]

File: CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/sna/centrality/BetweennessCentralityPlugin.java [hunk 2]
```diff
@@ -153,23 +153,31 @@ public void edit(final GraphWriteMethods graph, final PluginInteraction interact
...
             if (normaliseByPossible) {
                 if (normaliseConnectedComponents) {
                     final float subgraphVertexCount = subgraphs[vertexPosition].cardinality();
+                    betweennessAttributeValue = betweennesses[vertexPosition] / (((subgraphVertexCount - 1) * (subgraphVertexCount - 2)) / 2);
                     graph.setFloatValue(betweennessAttribute, vertexId, betweennesses[vertexPosition] / (((subgraphVertexCount - 1) * (subgraphVertexCount - 2)) / 2));
```
Comment (cygnus-x-1) [inline CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/sna/centrality/BetweennessCentralityPlugin.java:161]: remove all these `graph.setFloatValue` statements as your new one replaces them.

**Review by cygnus-x-1 — CHANGES_REQUESTED** [review]

File: CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/sna/centrality/BetweennessCentralityPlugin.java (hunk 2 above)
Comment (Nova-2119) [reply CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/sna/centrality/BetweennessCentralityPlugin.java:161]: Whoops, forgot to remove them...my bad, that's quite a glaring omission.

**Review by antares1470 — APPROVED** [review]

**Review by arcturus2 — APPROVED** [review]
